[package]
name = "gsl-splines"
edition = "2024"
version = "0.1.0"
authors.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
GSL = "7.0.0"
